"""create laser_conversion_field on visit tabel

Revision ID: 42ce78438719
Revises: 44c95148d89c
Create Date: 2023-10-28 10:18:14.625412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ce78438719'
down_revision: Union[str, None] = '44c95148d89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE conversion_enum AS ENUM ('UNKNOWN', 'NOT_NEW', 'NEW_BOUGHT', 'NEW_NOT_BOUGHT')")
    op.add_column('visits', sa.Column('laser_conversion_status', sa.Enum('UNKNOWN', 'NOT_NEW', 'NEW_BOUGHT', 'NEW_NOT_BOUGHT', name='conversion_enum'), nullable=True, server_default='UNKNOWN'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'laser_conversion_status')
    op.execute("DROP TYPE conversion_enum")
    # ### end Alembic commands ###
