"""rename field on visit from client_name to visit_time

Revision ID: 15a8dfc04d17
Revises: 42ce78438719
Create Date: 2023-12-14 15:50:31.759129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a8dfc04d17'
down_revision: Union[str, None] = '42ce78438719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'client_name', new_column_name='visit_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'visit_time', new_column_name='client_name')
    # ### end Alembic commands ###
