"""create all tables

Revision ID: ae037e1b53ec
Revises: 
Create Date: 2023-10-23 15:13:58.058084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae037e1b53ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workdays',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('idle_time', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('visit_time', sa.String(), nullable=False),
    sa.Column('workday_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workday_id'], ['workdays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedures',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('gross', sa.Integer(), nullable=True),
    sa.Column('sub', sa.Boolean(), nullable=True),
    sa.Column('first', sa.Boolean(), nullable=True),
    sa.Column('sub_visits', sa.Integer(), nullable=True),
    sa.Column('prime_cost', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('manual_input', sa.Boolean(), nullable=True),
    sa.Column('manual_value', sa.Integer(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('sub_gross', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('procedures')
    op.drop_table('visits')
    op.drop_table('workdays')
    op.drop_table('users')
    # ### end Alembic commands ###
