"""empty message

Revision ID: 44c95148d89c
Revises: ae037e1b53ec
Create Date: 2023-10-23 15:33:23.213003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c95148d89c'
down_revision: Union[str, None] = 'ae037e1b53ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alarm_on', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alarm_on')
    # ### end Alembic commands ###
